language: python
install:
- pip install pytest
- pip install geojson
- pip install forked-path
- npm install -g geojson-merge
before_script: .travis/before_script.sh
#- geojson-merge mymap.topojson class-pins.topojson > newmap.topojson
script: py.test
deploy:
  provider: releases
  file: README.md
  skip_cleanup: true
  on:
    repo: halfaro1/travel-log
env: 
  global:
  - REPO="git@github.com:halfaro1/travel-log.git"
  - secure: ! '510797f5a534473df68d854235ef3af68edff810'
