language: python
install:
  - pip install pytest
  - pip install geojson
  - pip install forked-path
  - npm install -g geojson-merge
before_script:
  - geojson-merge mymap.geojson combinedmap.geojson > newmap.geojson
script: py.test
deploy:
  provider: script
  script: deploy-script.sh
    #- touch wohoo.md
    #- git add wohoo.md
    #- rm combinedmap.geojson
    #- mv newmap.geojson combinedmap.geojson
  #on:
#    branch: gh-pages
#branches:
  #only:
  #  - master
  #  - gh-pages
