language: python
install:
  - pip install pytest
  - pip install geojson
  - pip install forked-path
  - npm install -g geojson-merge
before_script:
  - geojson-merge mymap.geojson combinedmap.geojson > newmap.geojson
script: py.test
deploy:
  provider: script
  script: bash deploy-script.sh
    #- touch wohoo.md
    #- git add wohoo.md
    #- rm combinedmap.geojson
    #- mv newmap.geojson combinedmap.geojson
  #on:
#    branch: gh-pages
#branches:
#  only:
#    - master
  #  - gh-pages
env:
  global:
    - GITHUB_REPO: "halfaro1/travel-log"
    - secure: "CSrojHtqNseP2DyTrbnllC2HTNTZV6B+wOsuIdO5M8ziZeyOx8J3yBJzL5I58GOW7tLHBwPyWVh03mbGgC9AvUz1WyuastSxG9GOMB3FwWqbrkvM/BpeFQ1qHhZa60miNEkgOcIsdnZmmD+k7bF9Yfm3rOqQYbak6AaiG+i84k0mUDRURzHsLbkalIyupycJM2S8LxAaD/9c2W4+s85XmME8OZb8ISeURXy9AzQt1cn5Ed71wRK5mH44kyHmCVhRjEok72IzARUywRvgp16vOdd+6RtKd8hc8l754+Fxy8ng6SR0er2u9/aH0ofvYIsJ65t8ZbBUfUKauTwTWnCPvG8gbzcgh1nSkEu0/Bv9C+/Bdy+s85x/dY7swc40TL3VxFfC5mvbvigPB3KKhU6kpPLU2JQnVi4FhEVICDv/IMWMAqxTgtRrWzhBxSFma/Rkf3bsXZSmZiHoaepvzDIiZgT4/Q3LajQzg6pcFmRdfnHPz2cNr8zstcUIFS9V/7q9xMv57+Kwh0kYeHn3kTG1BJlQpPGCV55E9FL5jpKIhEAC3VzzOVgEwad5vpCu+A47E7jQl57kqaPUY8VhfN2l5pQO2nfLtK4saewxWD+SPMLxwt/Jy8Hzfc2JBahK2NDJLXk40EpKq29LOJAgvHzBSn3wGkFbYjkCoRGPoRSbHlg="
