language: python
install:
  - pip install pytest
  - pip install geojson
  - pip install forked-path
  - npm install -g geojson-merge
before_script:
  - geojson-merge mymap.geojson combinedmap.geojson > newmap.geojson
script: py.test
deploy:
  provider: script
  script:
    - rm combinedmap.geojson
    - mv newmap.geojson combinedmap.geojson
    - git add -A
    - git commit -m "add new file"
  on:
    branch: master
branches:
  only:
    - master
