language: python
install:
  - pip install pytest
  - pip install geojson
  - pip install forked-path
  - npm install -g geojson-merge
before_script:
  - geojson-merge mymap.geojson combinedmap.geojson > combinedmap.geojson
script: py.test
